shipment:
  ghn:
    url: ${GHN_API_URL:https://dev-online-gateway.ghn.vn/shiip/public-api}
    apiToken: ${GHN_API_TOKEN:demo-token}
    shopId: ${GHN_SHOP_ID:0}
    address:
      fromDistrictId: ${GHN_FROM_DISTRICT_ID:1454}
      fromWardCode: ${GHN_FROM_WARD_CODE:21211}
    defaultBook:
      length: ${GHN_DEFAULT_LENGTH:20}
      width: ${GHN_DEFAULT_WIDTH:15}
      height: ${GHN_DEFAULT_HEIGHT:10}
      weight: ${GHN_DEFAULT_WEIGHT:500}
