spring:
  application:
    name: bookstore-shipping-service
  profiles:
    active: dev
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 15000
          ghn-api-client:
            read-timeout: 30000

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
