clients:
  ghn:
    url: https://dev-online-gateway.ghn.vn/shiip/public-api

shipment:
  ghn:
    url: https://dev-online-gateway.ghn.vn/shiip/public-api
    apiToken: 4149566a-b2e0-11f0-b040-4e257d8388b4
    shopId: 197778
    shop:
      name: "Bookstore Shop"
      phone: "0374425748"
      address: "123 Street Name"
      ward: "Phường 1"
      district: "Quận Gò Vấp"
      province: "Hồ Chí Minh"
    address:
      fromDistrictId: 1461
      fromWardCode: 21301
      fromProvinceId: 202
    defaultBook:
      length: 20
      width: 15
      height: 2
      weight: 300
