spring:
  application:
    name: bookstore-shipping-service
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
