apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://bookstore-db-do-user-36177370-0.h.db.ondigitalocean.com:25060/bookstore_shipping?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_RABBITMQ_HOST: "143.198.204.41"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_VIRTUAL_HOST: "bookstore"
  GHN_API_URL: "https://dev-online-gateway.ghn.vn/shiip/public-api"
  GHN_SHOP_ID: "200381"
  GHN_SHOP_NAME: "Bookstore Shop"
  GHN_SHOP_PHONE: "0704500354"
  GHN_SHOP_ADDRESS: "123 Le Van Tho"
  GHN_SHOP_WARD: "Phường 1"
  GHN_SHOP_DISTRICT: "Quận Gò Vấp"
  GHN_SHOP_PROVINCE: "Hồ Chí Minh"
  GHN_FROM_WARD_CODE: "21301"
  GHN_FROM_DISTRICT_ID: "1461"
  GHN_FROM_PROVINCE_ID: "202"
  GHN_DEFAULT_LENGTH: "20"
  GHN_DEFAULT_WIDTH: "15"
  GHN_DEFAULT_HEIGHT: "2"
  GHN_DEFAULT_WEIGHT: "300"
